#ifndef MULTIPROCESSSYSTEM_GLOBAL_H
#define MULTIPROCESSSYSTEM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MULTIPROCESSSYSTEM_LIBRARY)
#  define MULTIPROCESSSYSTEM_EXPORT Q_DECL_EXPORT
#else
#  define MULTIPROCESSSYSTEM_EXPORT Q_DECL_IMPORT
#endif

#endif // MULTIPROCESSSYSTEM_GLOBAL_H
