# This is a basic workflow to help you get started with Actions

name: Qt 5 on Linux

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install Qt action
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.*'
          host: 'linux'
          target: 'desktop'
        
      - name: configure
        working-directory: ${{ github.workspace }}
        run: qmake

      - name: make
        working-directory: ${{ github.workspace }}
        run: make

      - name: make sub-examples
        working-directory: ${{ github.workspace }}
        run: make sub-examples
