name: Qt 5 on macOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.*'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'

    - name: configure
      working-directory: ${{ github.workspace }}
      run: qmake

    - name: make
      working-directory: ${{ github.workspace }}
      run: make

    - name: make sub-examples
      working-directory: ${{ github.workspace }}
      run: make sub-examples
