name: Qt 5 on Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
 
    - name: Setup MSVC Developer Command Prompt
      uses: TheMrMilchmann/setup-msvc-dev@v2.0.0
      with:
        arch: x64

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.*'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: configure
      working-directory: ${{ github.workspace }}
      run: qmake

    - name: make
      working-directory: ${{ github.workspace }}
      run: nmake

    - name: make sub-examples
      working-directory: ${{ github.workspace }}
      run: nmake sub-examples
